#!/bin/bash
set -xe

#=========================
# Build and install RPM
#=========================
"$WORKSPACE/jenkins/common/build_install_rpm"

#==========================
# Start service
#==========================
sudo service httpd restart
